### ISSUE TITLE
Lockups on BeagleBone Black

### ISSUE THREAD

**Issue by synaptic-axon** [AD-Vega/rtl-power-fftw#10]
Hello,

I've been using this on a BeagleBone Black and really like it over the rtl_power program.  However, it has been locking up on me periodically.  I get rtl_power_fftw zombies and subsequent invocations of the program just hang.  

After this happens, I see errors like this in dmesg and /var/log/debug:

[  843.116587] usb 1-1: usbfs: usb_submit_urb returned -121
[ 1429.746645] usb 1-1: usbfs: usb_submit_urb returned -121
[ 1753.917133] usb 1-1: usbfs: usb_submit_urb returned -121
[ 1872.758512] usb 1-1: usbfs: usb_submit_urb returned -121
[ 1989.703487] usb 1-1: usbfs: usb_submit_urb returned -121
[ 2361.264800] usb 1-1: usbfs: usb_submit_urb returned -121
[ 2361.936215] usb 1-1: usbfs: usb_submit_urb returned -121
[ 2394.323512] usb 1-1: usbfs: usb_submit_urb returned -121
[ 2440.178307] usb 1-1: usbfs: usb_submit_urb returned -121
[ 3197.126711] musb_ep_program 896: broken !rx_reinit, ep2 csr 0203
[ 3291.558145] usb 1-1: usbfs: usb_submit_urb returned -121
[ 3341.844593] usb 1-1: usbfs: usb_submit_urb returned -121

root@beaglebone:~# tail /var/log/debug
Jan 13 23:42:41 beaglebone kernel: [15351.510607] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 13 23:46:13 beaglebone kernel: [15563.478408] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 13 23:46:21 beaglebone kernel: [15571.150976] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 13 23:49:09 beaglebone kernel: [15739.249629] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 13 23:53:32 beaglebone kernel: [16002.475321] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 14 00:01:13 beaglebone kernel: [16463.588125] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 14 00:01:25 beaglebone kernel: [16476.115999] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 14 00:04:40 beaglebone kernel: [16670.283887] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 14 00:08:43 beaglebone kernel: [16913.425003] usb 1-1: usbfs: usb_submit_urb returned -121
Jan 14 00:10:34 beaglebone kernel: [17024.671561] usb 1-1: usbfs: usb_submit_urb returned -121

root@beaglebone:~# uname -a
Linux beaglebone 4.1.12-ti-r29 #1 SMP PREEMPT Mon Nov 9 22:46:19 UTC 2015 armv7l GNU/Linux

This is the only USB device on the bus.  I don't know if it's related to rtl-power-fftw but thought I'd run it by you just in case it is something you've seen with the program before.

Any thoughts?

**Comment by kukabu** [comment]
which version of the libusb? Looks like http://www.libusb.org/ticket/56

**Comment by KlemenBlokar** [comment]
I think we haven't seen this one before. I would be glad if it were indeed libusb at fault here as I don't know where we would cause this. :-)

**Comment by synaptic-axon** [comment]
Yeah, it's a strange one.  I'm expecting that patch to be in this kernel but I still need to check the source.  This has been working fine all day today.  

My other suspicion is an intermittent power issue since I'm powering the beaglebone and rtlsdr device from USB.

I appreciate the feedback.  Just need to do some more diligence now.  I'm thinking it's not related to rtl-power-fftw though so feel free to close this issue.

**Comment by KlemenBlokar** [comment]
Ok, I will close the issue as invalid for now, but feel free to reopen it if suspicions will turn towards rtl-power-fftw again. And please inform us about what you found out - it could help someone someday. :-)
