### ISSUE TITLE
'floor' was not declared in this scope.

### ISSUE THREAD

**Issue by sgrax** [AD-Vega/rtl-power-fftw#13]
I'm trying to build the latest git sources but this is what I run into:
```
rtl-power-fftw/src/params.cxx: In constructor ‘Params::Params(int, char**)’:
rtl-power-fftw/src/params.cxx:171:59: error:  floor’ was not declared in this scope
       buf_length = floor((double)buf_length/base_buf + 0.5) * base_buf;
                                                           ^
CMakeFiles/rtl_power_fftw.dir/build.make:158: recipe for target 'CMakeFiles/rtl_power_fftw.dir/src/params.cxx.o' failed
make[2]: *** [CMakeFiles/rtl_power_fftw.dir/src/params.cxx.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rtl_power_fftw.dir/all' failed
make[1]: *** [CMakeFiles/rtl_power_fftw.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wazzard** [comment]
You need to include do an #include <math.h> in that params.cxx file

**Comment by wazzard** [comment]
include <math.h> in params.cxx

**Comment by wazzard** [comment]
for some reason this is not allowing my full comment, you need to include math dot h in the params.cxx

**Comment by alajovic** [comment]
Thanks, I have added the missing include, so the latest version in master branch should build without problems. @sgrax: I'm just curious: which system are you using? I am surprised that I have not stumbled upon this problem before.

**Comment by wazzard** [comment]
I’m using the NetRunner Rolling distro, which is based on Arch
