### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [AD-Vega/rtl-power-fftw#26]
Hi, can you add the following topics to this repository?
* https://github.com/topics/sdr
* https://github.com/topics/rtl-sdr
* https://github.com/topics/rtl-power

Thanks!

**Comment by KlemenBlokar** [comment]
Thank you for the tip, I did not even know of this github feature. :+1:

**Comment by mendel5** [comment]
Sure, thank you!
