### ISSUE TITLE
pure virtual method called 

### ISSUE THREAD

**Issue by kukabu** [AD-Vega/rtl-power-fftw#5]
Hello

it's not work for me :(

```shell
$ rtl_power_fftw -f 433M -t 10 -b 512 -d 0
Found Rafael Micro R820T tuner
Available gains (in 1/10th of dB): 0, 9, 14, 27, 37, 77, 87, 125, 144, 157, 166, 197, 207, 229, 254, 280, 297, 328, 338, 364, 372, 386, 402, 421, 434, 439, 445, 480, 496
Selected nearest available gain: 372 (37.2 dB)
Exact sample rate is: 2000000.052982 Hz
Actual sample rate: 2000000 Hz
Number of bins: 512
Total number of (complex) samples to collect: 20000256
Buffer length: 819200
Number of device readouts: 49
Number of averaged spectra: 39063
Estimated time of measurements: 10.0352 seconds
Device tuned to: 433000000 Hz
Acquisition started at 2015-12-03 05:04:29 UTC
pure virtual method called
terminate called without an active exception
Aborted
```

**Comment by KlemenBlokar** [comment]
Hi,
can you please tell me what version of GCC, librtlsdr and fftw do you have on your system?
Also if you can tell me what distro you are using, I could try to reproduce the problem.

**Comment by kukabu** [comment]
Hi
```
gcc-4.8 (Raspbian 4.8.2-21~rpi3rpi1) 4.8.2

ii  libfftw3-3:armhf                  3.3.2-3.1             armhf                 Library for computing Fast Fourier Transforms
ii  librtlsdr0:armhf                  0.5.3-5               armhf                 Software defined radio receiver for Realtek RTL2832U (library)
```

I using Raspbian Wheezy.

**Comment by KlemenBlokar** [comment]
For this, it will take a while before I will be able to test myself.
Can you tell me, does the error come soon after the line "Acquisition started ..." is printed out, or does it wait for about 10 seconds before it fails?

**Comment by kukabu** [comment]
No waiting.

**Comment by KlemenBlokar** [comment]
I set up a debug branch in repository.
Could you compile the source from that branch and paste me the output?

**Comment by kukabu** [comment]
Hm... I builded rtl_power_fftw with flags
```shell
export CC=gcc-4.8
export CXX=g++-4.8
export CFLAGS="-march=armv6zk -mcpu=arm1176jzf-s -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
export CXXFLAGS="$CFLAGS"
```
I unsets CFLAGS and CFLAGS, rebuild rtl_power_fftw and it's works now.

**Comment by KlemenBlokar** [comment]
Ah, so it could be an issue with c++11 threads. I was thinking in that direction after a bit of searching for similar problems.
I'll close the issue as it is now working.

**Comment by kukabu** [comment]
Thanks for your help.
