### ISSUE TITLE
Raspberry Pi GPU acceleration.

### ISSUE THREAD

**Issue by kukabu** [AD-Vega/rtl-power-fftw#6]
Hello

It will be great if the rtl-power-fftw can use Raspberry Pi GPU for FFT.

http://www.aholme.co.uk/GPU_FFT/Main.htm

**Comment by KlemenBlokar** [comment]
Hi,

as far as I know, there is a project to make the GPU fft library a drop-in replacement for fftw.
Check this out:
https://github.com/gpu-fftw/gpu_fftw

**Comment by kukabu** [comment]
WoW! I don't know about it. Thanks

**Comment by kukabu** [comment]
The gpu_fftw seems abandoned,  it's a pity.

**Comment by KlemenBlokar** [comment]
Oh, that is unfortunate.
However we wanted to create a more universal program than just for RPi, so fftw is the only reasonable option. Furthermore, the GPU_FFT is very limited in the sense that it only does FFT with bin sizes of powers of two...

**Comment by alajovic** [comment]
This is a rather platform-specific request and since there seems to be a lack of incentive for doing it, I am closing this issue as WONTFIX. Shoud anybody find this to be a interesting challange, they are most welcome to try their luck. Please report back if you manage to get it working.
